apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: deploy-nextjs-tekton-e2e-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: nextjs-tekton-e2e
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea-7-timothy-credo-tekton-e2e
    - name: image-repo
      value: quay.io/timothy_credo/nextjs-tekton-e2e
  pipelineRef:
    name: deploy-nextjs-tekton-e2e
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce 
          resources:
            requests:
              storage: 1Gi
    - name: gitops-repository
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
          - ReadWriteOnce
    - name: git-credentials
      secret:
        secretName: git-credentials